version: '3.4'

services:
    rabbitmq:
        container_name: rabbitmq
        restart: always
        ports:
            - "5672:5672"
            - "15672:15672"

    cartdb:
        container_name: cartdb
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin1234
            - POSTGRES_DB=CartDb
        restart: always
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    servicediscoverydb:
        container_name: servicediscoverydb
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=admin1234
        restart: always
        ports:
            - "1433:1433"

    unicorn.eshop.cart:
        container_name: unicorn.eshop.cart
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - CartHostSettings__DbConnectionString=Server=cartdb;Port=5432;Database=CartDb;User Id=admin;Password=admin1234;
            - CartHostSettings__OneWayCommunicationSettings__ConnectionString=amqp://guest:guest@rabbitmq:5672
            - CartHostSettings__ServiceDiscoverySettings__Url=http://unicorn.core.services.servicediscovery
        depends_on:
            - cartdb
            - rabbitmq
            - unicorn.core.services.servicediscovery
            - unicorn.core.services.apigateway.ocelot
        ports:
            - "8000:80"
            - "8001:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    unicorn.core.services.servicediscovery:
        container_name: unicorn.core.services.servicediscovery
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ServiceDiscoveryHostSettings__DbConnectionString=Server=servicediscoverydb;Database=ServiceDiscoveryDb;User Id=sa;Password=admin1234;
        depends_on:
            - servicediscoverydb
        ports:
            - "8002:80"
            - "8003:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    unicorn.eshop.discount:
        container_name: unicorn.eshop.discount
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - DiscountHostSettings__DbConnectionString=Server=cartdb;Port=5432;Database=CartDb;User Id=admin;Password=admin1234;
            - DiscountHostSettings__OneWayCommunicationSettings__ConnectionString=amqp://guest:guest@rabbitmq:5672
            - DiscountHostSettings__ServiceDiscoverySettings__Url=http://unicorn.core.services.servicediscovery
        depends_on:
            - unicorn.core.services.servicediscovery
            - rabbitmq
            - unicorn.core.services.apigateway.ocelot
        ports:
            - "8004:80"
            - "8005:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    unicorn.eshop.catalog:
        container_name: unicorn.eshop.catalog
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - CatalogHostSettings__OneWayCommunicationSettings__ConnectionString=amqp://guest:guest@rabbitmq:5672
            - CatalogHostSettings__ServiceDiscoverySettings__Url=http://unicorn.core.services.servicediscovery
        depends_on:
            - unicorn.core.services.servicediscovery
            - rabbitmq
            - unicorn.core.services.apigateway.ocelot
        ports:
            - "8006:80"
            - "8007:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    unicorn.core.services.apigateway.ocelot:
        container_name: unicorn.core.services.apigateway.ocelot
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
            - "8008:80"
            - "8009:443"
        volumes:
            - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
            - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

    #unicorn.core.services.authentication.openiddict:
    #    container_name: unicorn.core.services.authentication.openiddict
    #    environment:
    #        - ASPNETCORE_ENVIRONMENT=Development
    #        - ASPNETCORE_URLS=https://+:443;http://+:80
    #        #- ASPNETCORE_Kestrel__Certificates__Default__Password=admin1234
    #        #- ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/Unicorn.eShop.CartService.pfx
    #        #- ASPNETCORE_Kestrel__Certificates__Default__Path=/certificates/UnicornCertificate.pem
    #        #- ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/certificates/UnicornCertificate-key.pem
    #        - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/certificates/2.pem
    #        - ASPNETCORE_Kestrel__Certificates__Default__KeyPath=/root/certificates/2-key.pem
    #    ports:
    #        - "8002:80"
    #        - "8003:443"
    #    volumes:
    #        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
    #        - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    #        - C:/Src/unicorn-project-microservices/certificates:/root/certificates
    #        #- $PWD/app/certificates:/certificates