version: '3.4'

services:
  cartdb:
    image: postgres

  unicorn.eshop.cartservice:
    image: ${DOCKER_REGISTRY-}unicorneshopcartservice
    build:
      context: .
      dockerfile: eShop/Unicorn.eShop.CartService/Dockerfile

volumes:
  postgres_data: