version: '3.4'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine

    cartdb:
        image: postgres

    servicediscoverydb:
        image: mcr.microsoft.com/mssql/server:2019-latest

    unicorn.eshop.cart:
        image: ${DOCKER_REGISTRY-}unicorneshopcart
        build:
            context: .
            dockerfile: eShop/cart/Unicorn.eShop.Cart/Dockerfile

    unicorn.eshop.discount:
        image: ${DOCKER_REGISTRY-}unicorneshopdiscount
        build:
            context: .
            dockerfile: eShop/discount/Unicorn.eShop.Discount/Dockerfile

    unicorn.eshop.catalog:
        image: ${DOCKER_REGISTRY-}unicorneshopcatalog
        build:
            context: .
            dockerfile: eShop/catalog/Unicorn.eShop.Catalog/Dockerfile

    unicorn.core.services.servicediscovery:
        image: ${DOCKER_REGISTRY-}unicorncoreservicesservicediscovery
        build:
            context: .
            dockerfile: core/services/service-discovery/Unicorn.Core.Services.ServiceDiscovery/Dockerfile

    unicorn.core.services.apigateway.ocelot:
        image: ${DOCKER_REGISTRY-}unicorn.core.services.apigateway.ocelot
        build:
            context: .
            dockerfile: core/services/api-gateway/Unicorn.Core.Services.ApiGateway.Ocelot/Dockerfile

    #unicorn.core.services.authentication.openiddict:
    #    image: ${DOCKER_REGISTRY-}unicorncoreservicesauthenticationopeniddict
    #    build:
    #        context: .
    #        dockerfile: core/services/authentication/Unicorn.Core.Services.Authentication.OpenIddict/Dockerfile

volumes:
    postgres_data: